name: Milestone Worker

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.3
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
    - name: Install pack
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        pack-version: 0.18.0
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    # target deploy repos
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-deploy=repo.spring.io \
          --repo-deploy-releases=libs-staging-local \
          --repo-deploy-snapshots=libs-staging-local
        echo JFROG_CLI_BUILD_NAME=spring-cloud-skipper-27x-milestone >> $GITHUB_ENV
        echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV

    # zoo extract and ensure
    - name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: |
          BUILD_ZOO_HANDLER_milestone_version
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version
          BUILD_ZOO_HANDLER_spring_cloud_deployer_version
          BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version
          BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version
          BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version
          BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version

    # build and publish to configured target
    - name: Build and Publish
      run: |
        jfrog rt mvn build-helper:parse-version versions:set \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DprocessAllModules=true \
          -DgenerateBackupPoms=false \
          -Dartifactory.publish.artifacts=false \
          -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-'${BUILD_ZOO_HANDLER_milestone_version} \
          -B
        echo BUILD_ZOO_HANDLER_spring_cloud_skipper_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
        jfrog rt mvn versions:update-parent \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -DparentVersion='['${BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version}']' \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-dataflow-common.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version} \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-deployer.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_version} \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-deployer-local.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version} \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-deployer-cloudfoundry.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version} \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-deployer-kubernetes.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version} \
          -B
        jfrog rt mvn versions:set-property \
          -gs .github/settings.xml \
          -Pstagingmilestone \
          -DgenerateBackupPoms=false \
          -Dproperty=spring-cloud-common-security-config.version \
          -DnewVersion=${BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version} \
          -B
        jfrog rt build-clean
        jfrog rt mvn clean install \
          -gs .github/settings.xml \
          -P-spring,stagingmilestone,restdocs,asciidoctordocs \
          -DskipTests -U -B
        jfrog rt build-publish
        echo BUILD_ZOO_HANDLER_spring_cloud_skipper_buildname=spring-cloud-skipper-27x-milestone >> $GITHUB_ENV
        echo BUILD_ZOO_HANDLER_spring_cloud_skipper_buildnumber=$GITHUB_RUN_NUMBER >> $GITHUB_ENV

    # zoo tag
    - name: Tag Release
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        tag-release-branch: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}
        tag-release-tag: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}
        tag-release-tag-prefix: v

    # build image to local repo to get pushed
    - name: Build Image
      env:
        TAG: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}
      run: |
        pack build \
          --path spring-cloud-skipper-server/target/spring-cloud-skipper-server-$TAG.jar \
          --builder gcr.io/paketo-buildpacks/builder:0.1.99-base \
          --env BP_JVM_VERSION=8 springcloud/spring-cloud-skipper-server:$TAG-jdk8
        pack build \
          --path spring-cloud-skipper-server/target/spring-cloud-skipper-server-$TAG.jar \
          --builder gcr.io/paketo-buildpacks/builder:0.1.99-base \
          --env BP_JVM_VERSION=11 springcloud/spring-cloud-skipper-server:$TAG-jdk11

    # docker hub login
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # push image
    - name: Push image
      env:
        TAG: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}
      run: |
        docker push springcloud/spring-cloud-skipper-server:$TAG-jdk8
        docker push springcloud/spring-cloud-skipper-server:$TAG-jdk11
        docker tag springcloud/spring-cloud-skipper-server:$TAG-jdk11 springcloud/spring-cloud-skipper-server:$TAG
        docker push springcloud/spring-cloud-skipper-server:$TAG

    # zoo success
    - name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "build-succeed"
          }

    # zoo failure
    - name: Notify Build Failure Zoo Handler Controller
      if: ${{ failure() }}
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "build-failed",
            "message": "spring-cloud-skipper failed"
          }
    # clean m2 cache
    - name: Clean cache
      run: |
        find ~/.m2/repository -type d -name '*SNAPSHOT' | xargs rm -fr
